sudo: false

language: php

php:
  - 7.4
  - 8.0

env:
  global:
    - deps=high

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: deps=high
    - php: 8.0
      env: deps=low

install:
  - if [ "$deps" = "no" ]; then composer install; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
  - if [ "$deps" = "high" ]; then composer update; fi

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
