sudo: false

language: php

php:
  - 7.4
  - 8.0

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: deps=low
    - php: 8.0
      env: deps=low

install:
  - |
    # Installing dependencies ...
    if [[ $deps = "low" ]]; then
      composer update --prefer-dist --prefer-lowest
    else
      composer install --prefer-dist
    fi

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
