sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - deps=high

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 5.6
    - php: 7.1
      env: DEPENDENCIES=beta
  allow_failures:
    - php: hhvm

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;

install:
  - if [ "$deps" = "no" ]; then composer install; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
  - if [ "$deps" = "high" ]; then composer update; fi

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
